# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 06 Dec 2016 02:29:06 +0000
*               @ALL          1
*               @user         8
