<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Sun, 25 Dec 2016 10:26:28 +0000
 */

$conf['title'] = 'Driver';
$conf['license'] = 'cc-by-sa';
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['plugin']['discussion']['adminimport'] = 1;
$conf['plugin']['discussion']['newestfirst'] = 1;
$conf['plugin']['discussion']['moderate'] = 1;
$conf['plugin']['discussion']['userealname'] = 0;
$conf['plugin']['pagelist']['showcomments'] = 1;
$conf['tpl']['mnml-blog']['mnmlblog_sidebarnav'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_copyright'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_copyright_default'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_search'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_qrcodebox'] = '0';

// end auto-generated content
